version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install awscli

  build:
    commands:
      - echo Validating CloudFormation Template
      - ls -al
      - find .
      - aws cloudformation validate-template --template-body file://template.yaml

artifacts:
  files:
    - template.yaml
