version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing AWS CLI...
      - pip install --upgrade awscli
  build:
    commands:
      - echo Validating CloudFormation Template
      - aws cloudformation validate-template --template-body file://template.yaml

artifacts:
  files:
    - template.yaml
