phases:
  build:
    commands:
      - echo Validating CloudFormation Templates
      - ls -al
      - find .
      - aws cloudformation validate-template --template-body file://cloudformation-pipeline/template.yaml
      - aws cloudformation validate-template --template-body file://template.yaml
artifacts:
  files:
    - cloudformation-pipeline/template.yaml
    - template.yaml
