version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - pip install awscli
  build:
    commands:
      - echo Listing files in current directory:
      - ls -al
      - echo Listing files recursively:
      - find .
      - echo Validating CloudFormation Template
      - aws cloudformation validate-template --template-body file://cloudformation-pipeline/template.yaml

artifacts:
  files:
    - cloudformation-pipeline/template.yaml
